version: '3'
services:
  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    container_name: sensors_data_mysql
    ports:
      - 3306:3306
    tty: true
  app:
    build:
      context: .
    restart: always
    container_name: sensors_app
    environment:
      - SENSORS_HOST=192.168.0.49
      - RELAYS_HOST=192.168.0.8:8072
      - MYSQL_CONNECTION=db_user:db_password@tcp(db:3306)/db_name
      - GIN_MODE=release
    ports:
      - 8084:8080
    tty: true
    depends_on:
      - db
    links:
      - db