version: '3'
services:
  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    container_name: sensors_data_mysql
    ports:
      - 3306:3306
    tty: true
  app:
    build:
      context: .
    restart: always
    container_name: sensors_app
    environment:
      - PORT_ENV=8084
      - HOST_SENSORS=192.168.0.49
      - HOST_RELAYS=192.168.0.8:8082
      - GIN_MODE=release
    ports:
      - 8084:8084
    tty: true
    depends_on:
      - db
    links:
      - db