version: '3'
services:
  db:
    image: mysql:5.6
#    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    container_name: golang_gin_db
    ports:
      - 3306:3306
    tty: true
  app:
    build:
      context: .
    restart: always
    container_name: golang_gin_app
    ports:
      - 8084:8084
    tty: true
    depends_on:
      - db
    links:
      - db